### ISSUE TITLE
turboSETI allocates memory from multiple GPUs

### ISSUE THREAD

**Issue by lacker** [UCBerkeleySETI/turbo_seti#264] opened 2021-07-19 22:59 UTC
**Describe the bug**

turboSETI appears to be allocating GPU memory from multiple GPUs, and only using a zero or small amount from most of them. This seems either buggy or just mildly inefficient.

**To Reproduce**

I used the command line
`turboSETI /datag/pipeline/AGBT21A_996_44/blc27/blc27_guppi_59383_49299_TIC102713734_0036.rawspec.0000.h5 -g y`
on blpc2 but probably any use of just `-g y` will reveal this problem.

Then I checked nvidia-smi to see what this process was allocating and noticed an allocation on multiple GPUs.

**Expected behavior**

To only allocate memory on one gpu

**Screenshots**

some nvidia-smi output:

```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A    788874      C   python                              0MiB |
|    2   N/A  N/A    788874      C   python                            825MiB |
|    3   N/A  N/A    788874      C   python                              0MiB |
+-----------------------------------------------------------------------------+
Mon Jul 19 15:53:25 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.04    Driver Version: 455.23.04    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:18:00.0 Off |                  N/A |
| 22%   41C    P8    16W / 250W |      3MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:3B:00.0 Off |                  N/A |
|  0%   41C    P8     7W / 180W |      2MiB /  8119MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:86:00.0 Off |                  N/A |
| 52%   72C    P2    83W / 250W |    827MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:AF:00.0 Off |                  N/A |
|  0%   38C    P8     9W / 250W |      2MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A    788874      C   python                              0MiB |
|    2   N/A  N/A    788874      C   python                            825MiB |
|    3   N/A  N/A    788874      C   python                              0MiB |
+-----------------------------------------------------------------------------+
```

**Setup**

blpc2 at berkeley

**Comment by texadactyl** [comment] 2021-07-30 22:34
@luigifcruz Have any idea why this is happening?

**Comment by luigifcruz** [comment] 2021-08-01 16:04
I'm not sure. I'll need to debug this. This should use one GPU only.

**Comment by texadactyl** [comment] 2021-08-23 15:36
@luigifcruz If this is an Nvidia issue, just say so.  We can talk to Matt about how to bring it to their attention.

**Comment by texadactyl** [comment] 2021-09-02 16:54
Verified symptoms.  Someone is calling Kernels.__init__ a second time, the last time with no device ID or 0 specified.
```
numexpr.utils   INFO     Note: NumExpr detected 40 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
numexpr.utils   INFO     NumExpr defaulting to 8 threads.

turbo_seti version 2.1.12
blimpy version 2.0.28
h5py version 2.10.0

DEBUG no kernels specified
DEBUG Kernels __init__ gpu_id: 2
DEBUG Kernels _load_base using gpu_id: 2
HDF5 header info: {'DIMENSION_LABELS': array([b'time', b'feed_id', b'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 8421.386717353016, 'foff': -2.7939677238464355e-06, 'ibeam': 1, 'machine_id': 20, 'nbeams': 1, 'nbits': 32, 'nchans': 1048576, 'nifs': 1, 'rawdatafile': 'guppi_57650_67573_Voyager1_0002.0000.raw', 'source_name': 'Voyager1', 'src_dej': <Angle 12.183 deg>, 'src_raj': <Angle 17.16777333 hourangle>, 'telescope_id': 6, 'tsamp': 18.253611008, 'tstart': 57650.78209490741, 'za_start': 0.0}

Starting ET search with parameters: datafile=/datax/scratch/texadactyl/voyager/Voyager1.single_coarse.fine_res.h5, max_drift=4.0, min_drift=1e-05, snr=25.0, out_dir=./, coarse_chans=None, flagging=False, n_coarse_chan=1, kernels=None, gpu_id=2, gpu_backend=True, blank_dc=True, precision=1, append_output=False, log_level_int=20, obs_info={'pulsar': 0, 'pulsar_found': 0, 'pulsar_dm': 0.0, 'pulsar_snr': 0.0, 'pulsar_stats': array([0., 0., 0., 0., 0., 0.]), 'RFI_level': 0.0, 'Mean_SEFD': 0.0, 'psrflux_Sens': 0.0, 'SEFDs_val': [0.0], 'SEFDs_freq': [0.0], 'SEFDs_freq_up': [0.0]}

Computed drift rate resolution: 0.009566489757225039

DEBUG Kernels __init__ gpu_id: 0
find_doppler.0  INFO     Top hit found! SNR 30.612333, Drift Rate -0.392226, index 739933
find_doppler.0  INFO     Top hit found! SNR 245.709610, Drift Rate -0.373093, index 747929
find_doppler.0  INFO     Top hit found! SNR 31.220858, Drift Rate -0.392226, index 756037
```

**Comment by texadactyl** [comment] 2021-09-02 17:28
The second one is happening in the following ```find_doppler.py``` function and seems to benign i.e. no GPU is accessed even though a device ID is inadvertently set to 0:
```
def load_the_data(d, precision):
    data_obj = DATAH5(d['filename'],
                  f_start=d['f_start'],
                  f_stop=d['f_stop'],
                  coarse_chan=d['coarse_chan'],
                  n_coarse_chan=d['n_coarse_chan'],
                  gpu_backend=False,
                  precision=precision)
```
and ```DATAH5.__init__``` does preset to 0 but passes in the ```gpu_backend=False``` to ```Kernels.__init__```:

```
turbo_seti version 2.1.12
blimpy version 2.0.28
h5py version 2.10.0

DEBUG no kernels specified
DEBUG Kernels __init__ gpu_backend=True, gpu_id=2
DEBUG Kernels _load_base using gpu_id: 2
HDF5 header info: {'DIMENSION_LABELS': array([b'time', b'feed_id', b'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 8421.386717353016, 'foff': -2.7939677238464355e-06, 'ibeam': 1, 'machine_id': 20, 'nbeams': 1, 'nbits': 32, 'nchans': 1048576, 'nifs': 1, 'rawdatafile': 'guppi_57650_67573_Voyager1_0002.0000.raw', 'source_name': 'Voyager1', 'src_dej': <Angle 12.183 deg>, 'src_raj': <Angle 17.16777333 hourangle>, 'telescope_id': 6, 'tsamp': 18.253611008, 'tstart': 57650.78209490741, 'za_start': 0.0}

Starting ET search with parameters: datafile=/datax/scratch/texadactyl/voyager/Voyager1.single_coarse.fine_res.h5, max_drift=4.0, min_drift=1e-05, snr=25.0, out_dir=./, coarse_chans=None, flagging=False, n_coarse_chan=1, kernels=None, gpu_id=2, gpu_backend=True, blank_dc=True, precision=1, append_output=False, log_level_int=20, obs_info={'pulsar': 0, 'pulsar_found': 0, 'pulsar_dm': 0.0, 'pulsar_snr': 0.0, 'pulsar_stats': array([0., 0., 0., 0., 0., 0.]), 'RFI_level': 0.0, 'Mean_SEFD': 0.0, 'psrflux_Sens': 0.0, 'SEFDs_val': [0.0], 'SEFDs_freq': [0.0], 'SEFDs_freq_up': [0.0]}

Computed drift rate resolution: 0.009566489757225039

DEBUG Kernels __init__ gpu_backend=False, gpu_id=0     # <-------- caused by DATAH5.__init__

find_doppler.0  INFO     Top hit found! SNR 30.612333, Drift Rate -0.392226, index 739933
find_doppler.0  INFO     Top hit found! SNR 245.709610, Drift Rate -0.373093, index 747929
find_doppler.0  INFO     Top hit found! SNR 31.220858, Drift Rate -0.392226, index 756037
```

So, it looks like ```Kernels.__init__``` is only initialising a single gpu device by turbo_seti since I did not see a repeat of the ```DEBUG Kernels _load_base using gpu_id ...```.  I'll see if I can get some sense of which gpu is actually in use.

**Comment by texadactyl** [comment] 2021-09-02 17:33
While its running, I see this:
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   2625106      C   python3                             0MiB |
|    1   N/A  N/A   2625106      C   python3                             0MiB |
|    2   N/A  N/A   2625106      C   python3                           468MiB |
|    3   N/A  N/A   2625106      C   python3                             0MiB |
+-----------------------------------------------------------------------------+
```
So, my process appears on the status line of gpu 2 (the one specified) consuming 468 MiB and the other as consuming 0 MiB.

**Comment by texadactyl** [comment] 2021-09-02 17:38
@david-macmahon 
In your experience, is this cupy/cuda behaviour possible?

Our source code that calls ```use()```: https://github.com/UCBerkeleySETI/turbo_seti/blob/master/turbo_seti/find_doppler/kernels/__init__.py

**Comment by david-macmahon** [comment] 2021-09-02 18:01
Not sure how the python libs are initializing CUDA, but FWIW when running the `bandwidthTest` utility from the CUDA samples, the output of `nvidia-smi` only shows one line in the `Processes:` section of the output and that corresponds to the requested GPU. Specifically, it does not show any `0MiB` lines for other non-used GPUs.

**Comment by texadactyl** [comment] 2021-09-02 18:38
I stepped through the all the statements of the entire ```Kernel.__init__``` code.  Even with a selected gpu=2, I see nothing germain:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.04    Driver Version: 455.23.04    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   24C    P8    16W / 250W |      3MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:03:00.0 Off |                  N/A |
| 22%   26C    P8    15W / 250W |      3MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 00000000:83:00.0 Off |                  N/A |
| 22%   24C    P8    15W / 250W |      3MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 00000000:84:00.0 Off |                  N/A |
| 22%   25C    P8    15W / 250W |      3MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
```

**Comment by texadactyl** [comment] 2021-09-02 19:00
Found the section of ```find_doppler.py search()``` code where it is happening:
```
    input("\nPAUSE *BEFORE* tree_findoppler ...")
    tree_findoppler = fd.kernels.xp.zeros(tsteps * tdwidth, dtype=fd.kernels.float_type) + median_flag
    input("\nPAUSE *AFTER* tree_findoppler ...")
```

**Comment by texadactyl** [comment] 2021-09-02 19:15
So, this small program exhibits the same symptoms:
```
import cupy as cp
import importlib
xp = importlib.import_module("cupy")
xp.cuda.Device(2).use()
tree_findoppler = xp.zeros(16000000, dtype='float32') + 0.0
```

**Comment by texadactyl** [comment] 2021-09-02 19:24
@lacker @david-macmahon @luigifcruz 
Anyone have a theory?
The cupy.zeros() URL said very little about interfacing: https://docs.cupy.dev/en/stable/reference/generated/cupy.zeros.html#cupy.zeros

**Comment by lacker** [comment] 2021-09-07 21:53
It kind of looks like this bug occurs when you import cupy twice, when you import it once normally and you import it again using `importlib`. Then the problem isn't with `zeros` itself, the problem is that `cupy` and `xp` are referring to different copies of the cupy library here. In general the cupy module is implemented a bit weird - there are global settings that you can modify after importing - and also using importlib is a bit of a weird thing to do. I bet those two weird things just don't work correctly together. It isn't really clear from the cupy docs whether it's *supposed* to work to import it again later under a different name and to expect all the global configuration to work the same.

Fortunately both of the cupy imports are in the same file:

https://github.com/UCBerkeleySETI/turbo_seti/blob/master/turbo_seti/find_doppler/kernels/__init__.py

lines 45 and 83 both import cupy in a different way.

So if this theory is correct, all one has to do to fix this problem is to refactor Kernels to not do this double-importing.

**Comment by texadactyl** [comment] 2021-09-08 18:51
@lacker @luigifcruz 

It happens with one import.  The following small program comes up with the same symptom:
```
import importlib
xp = importlib.import_module("cupy")
xp.cuda.Device(2).use()
input("BEFORE: Go look at nvidia-smi output ...")
tree_findoppler = xp.zeros(3, dtype='float32')
input("AFTER: Go look at nvidia-smi output again ...")
```

During the 1st input statement, no GPU is in use by the process.
During the 2nd one, 3 GPUs are in use although only device 2 has memory allocated > 0.

Is this the culprit?  ```importlib.import_module("cupy")```

**Comment by luigifcruz** [comment] 2021-09-08 18:55
Does this happen if importing `cupy` like this?
```
import cupy as xp
xp.cuda.Device(2).use()
input("BEFORE: Go look at nvidia-smi output ...")
tree_findoppler = xp.zeros(3, dtype='float32')
input("AFTER: Go look at nvidia-smi output again ...")
```

**Comment by texadactyl** [comment] 2021-09-08 18:57
Yes it does!

**Comment by texadactyl** [comment] 2021-09-08 19:16
BEFORE:

**Comment by texadactyl** [comment] 2021-09-08 19:17
AFTER:
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A   2040224      C   heimdall                         2067MiB |
|    1   N/A  N/A   2137163      C   python3                             0MiB |
|    2   N/A  N/A   2137163      C   python3                           141MiB |
|    3   N/A  N/A   2040224      C   heimdall                            0MiB |
|    3   N/A  N/A   2137163      C   python3                             0MiB |
+-----------------------------------------------------------------------------+

```

**Comment by lacker** [comment] 2021-09-08 19:38
Ah yeah, I get the same behavior just doing:

```
import cupy
q = cupy.zeros(1000)
```

So, maybe this behavior of doing 0-size allocation on all GPUs is just how cupy is supposed to work.

**Comment by texadactyl** [comment] 2021-09-08 19:51
@lacker How many GPUs were allocated?  My guess: 3.

**Comment by texadactyl** [comment] 2021-09-08 20:19
Opened:
[https://github.com/cupy/cupy/issues/5720](url)

**Comment by wfarah** [comment] 2021-09-08 21:00
I'm interested in the `cupy` issue that you started, @texadactyl . I'm assuming it's not a `cupy` bug, per se, but maybe some inner workings of the nvidia driver.

**Comment by luigifcruz** [comment] 2021-09-08 21:07
I think this is a `cupy` bug or intended behavior. You need to explicitly specify the device you want to use to the CUDA driver. I guess we have to wait for the Cupy to make sure whether this is intended or not.

**Comment by texadactyl** [comment] 2021-09-08 21:11
From @lacker : 
"I did get everything working (ie, turboseti using only the one gpu that I wanted it to) using the CUDA_VISIBLE_DEVICES flag (and also CUDA_DEVICE_ORDER=PCI_BUS_ID to make the gpu order match with how nvidia-smi shows it).
"the CUDA_VISIBLE_DEVICES thing makes python only see one gpu"
"so you can't do Device(2).use() afterwards"
"because python considers it to be device 0 now"
"it's all kind of annoying because there is no official mapping of "which gpu is gpu 3" so all of nvidia-smi, cupy, and the default cuda device filter use different methods for ordering the gpus"

**Comment by texadactyl** [comment] 2021-09-08 21:12
I am closing this because nobody wants to fool around with nvidia's concept & misconcept of devices.

**Closed by texadactyl** 2021-09-08 21:12 UTC
Labels: review requested

**Comment by texadactyl** [comment] 2021-09-10 15:20
@david-macmahon @luigifcruz @lacker @telegraphic 

Update FWIW:  This seems to be an NVIDIA driver or reporting error (nvidia-smi):
[https://forums.developer.nvidia.com/t/mpi-multi-gpu-process-list-in-nvidia-smi/158008/8](url)

**Comment by texadactyl** [comment] 2022-05-04 22:36
FWIW, read: https://shawnliu.me/post/nvidia-gpu-id-enumeration-in-linux/

@david-macmahon @luigifcruz @lacker @telegraphic

Bottom line: Nothing wrong with the cudaSetDevice API or the CUDA_VISIBLE_DEVICES environment variable technique as long as CUDA_DEVICE_ORDER is set up correctly to PCI_BUS_ID; FASTEST_FIRST leads to unpredictable behaviour.

**Comment by texadactyl** [comment] 2022-05-04 22:39
Should export CUDA_DEVICE_ORDER=PCI_BUS_ID be set in /etc/profile as a data centre standard?

**Comment by lacker** [comment] 2022-05-04 22:48
The problem there is that it will make things slower by default when you just run a program that wants a single GPU....

**Comment by texadactyl** [comment] 2022-05-04 22:49
I was assuming that people will run nvidia-smi and pick a device that isn't busy.

**Comment by texadactyl** [comment] 2022-05-04 23:08
Would be nice:  export CUDA_DEVICE_ORDER=LEAST_BUSY
