### ISSUE TITLE
min_drift argument does not appear to work

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/turbo_seti#89] opened 2020-08-04 05:33 UTC
As noted by @ssmith00, Output .dat files clearly contain values below the minimum drift rate. Needs a fix and a unit test.

**Comment by texadactyl** [comment] 2020-12-26 17:06
@telegraphic @ssmith00 

1. By "values below the minimum drift rate", do you mean in absolute value or signed comparisons apply both in the min_drift= parameter value as well as in the filtering output to the DAT file?
2. In the rather complex if-statement in find_doppler.py::search_coarse_channel() beginning at line 342, is it using min_drift and max_drift correctly?
```
        if drift_block <= 0:
            complete_drift_range = data_obj.drift_rate_resolution * fd.kernels.np.array(
                range(-1 * tsteps_valid * (abs(drift_block) + 1) + 1,
                      -1 * tsteps_valid * (abs(drift_block)) + 1))
            sub_range = complete_drift_range[(complete_drift_range < min_drift) &
                                             (complete_drift_range >= -1 * max_drift)]
            logger.debug('drift_block <= 0: sub_range={}'.format(sub_range))
        else:
            complete_drift_range = data_obj.drift_rate_resolution * fd.kernels.np.array(
                range(1 + tsteps_valid * (drift_block - 1), 1 + tsteps_valid * (drift_block)))
            sub_range = complete_drift_range[(complete_drift_range >= min_drift) &
                                             (complete_drift_range <= max_drift)]
            logger.debug('drift_block > 0: sub_range={}'.format(sub_range))
```
3. Does the same criticism apply to max_drift?  Absolute value or signed parameter value and comparisons?

**Comment by texadactyl** [comment] 2020-12-26 17:31
I am not sure why the ```min_drift``` and ```max_drift``` filtering wasn't simply done in the subsequent loop [```for k, drift_rate in enumerate(sub_range)```] with ```sub_range``` replaced by ```complete_drift_range```:

```
        if drift_block <= 0:
            complete_drift_range = data_obj.drift_rate_resolution * fd.kernels.np.array(
                range(-1 * tsteps_valid * (abs(drift_block) + 1) + 1,
                      -1 * tsteps_valid * (abs(drift_block)) + 1))
            logger.debug('drift_block <= 0: complete_drift_range={}'.format(complete_drift_range))
        else:
            complete_drift_range = data_obj.drift_rate_resolution * fd.kernels.np.array(
                range(1 + tsteps_valid * (drift_block - 1), 1 + tsteps_valid * (drift_block)))
            logger.debug('drift_block > 0: complete_drift_range={}'.format(complete_drift_range))

        for k, drift_rate in enumerate(complete_drift_range):
            # DCP 2020.04 -- WAR to drift rate in flipped files
            if data_obj.header['DELTAF'] < 0:
                drift_rate = -drift_rate

            # Filter by drift rate boundaries
            if drift_rate < min_drift or drift_rate > max_drift: # use absolute or signed values?
                continue

            # Grab correct bit of spectrum out of the dedoppler tree output
            indx = ibrev[drift_indices[k]] * tdwidth
            fd.kernels.xp.copyto(hitsearch_buf, tree_findoppler[indx: indx + tdwidth])
            hitsearch(fd, hitsearch_buf, specstart, specend, snr,
                      drift_rate, data_obj.header, tdwidth, max_val, 0)

```

**Comment by texadactyl** [comment] 2020-12-27 15:27
More needs to be done E.g. adding a --min-drift parameter to seti_event.py and allowing a default max_drift value in FindDoppler __init__().

**Comment by texadactyl** [comment] 2020-12-27 17:17
@telegraphic , those of us (me and @luigifcruz) who are not as versed in radio telescope strategy could definitely use a live "chalk talk" (zoom) with you one of these days on the subject of *search_coarse_channel* strategy, especially this drift block loops.  Feel free to also include other issues such as #89 and #98.

I would suggest evening Perth time which would be morening Texas and Brazil time..

**Comment by texadactyl** [comment] 2021-01-30 14:01
It's failing in the Negative drift rates search.  The positive drift rate search seems to select the correct subset of the complete range for the given drift block number.

Existing code at version 2.0.7 line 391 and similar at line 399:
```
            for k, drift_rate in enumerate(complete_drift_range[(complete_drift_range < min_drift) & (
                    complete_drift_range >= -1 * max_drift)]):
```
It should be:
```
            for k, drift_rate in enumerate(complete_drift_range[(complete_drift_range <= -min_drift) &
                    (complete_drift_range >= -max_drift)]):
```
and more readable:
```
            bool_selected = (complete_drift_range <= -min_drift) & (complete_drift_range >= -max_drift)
            for k, drift_rate in enumerate(complete_drift_range[bool_selected]):
```
It is assumed that min_drift and max_drift are both absolute values on entry to search_coarse_channel().
Yes, the code around this area of the source is an eye test.
I had to write a simulator based on DEBUG logging output to see what was going on.
```
import numpy as np

drift_block_set  = np.arange(-5,5)
tsteps_valid  = 64
drift_rate_resolution = 0.01515824
min_drift = 1
max_drift = 4
BORDER = 100 * '-'

for drift_block in drift_block_set:
    if drift_block <= 0:
        complete_drift_range = drift_rate_resolution * np.array(
            range(-1 * tsteps_valid * (abs(drift_block) + 1) + 1,
                  -1 * tsteps_valid * (abs(drift_block)) + 1))
        bool_selected = (complete_drift_range <= -min_drift) & (complete_drift_range >= -max_drift)
        print("{} <=0  {}".format(drift_block, complete_drift_range))
        print("{} <=0  {}".format(drift_block, bool_selected))
        print(BORDER)

    if drift_block >= 0:
        complete_drift_range = drift_rate_resolution * np.array(
            range(tsteps_valid * (drift_block), tsteps_valid * (drift_block + 1)))
        bool_selected = (complete_drift_range >= min_drift) & (complete_drift_range <= max_drift)    
        print("{} >=0    {}".format(drift_block, complete_drift_range))
        print("{} >=0    {}".format(drift_block, bool_selected))
        print(BORDER)
```
Now, to run some tests to make sure that I did not break anything in the process.

I still don't like having those drift index files around without having the source code that generated them even though they seem to work.

**Comment by texadactyl** [comment] 2021-01-30 22:12
@telegraphic @ssmith00 
Closing this issue because I was able to reproduce the issue before PR #180 in a variety of files but afterwards, I observe the desired behviour.  Would it be possible for either of you to try again the case which provided the error symptoms?

**Comment by texadactyl** [comment] 2021-02-23 17:00
@telegraphic @ssmith00
I forgot to mention that turboSETI now accepts a minimum drift rate parameter (issue #178).

**Comment by texadactyl** [comment] 2021-02-23 21:08
Verified to still be broken somewhere in search_coarse_channel().

**Comment by texadactyl** [comment] 2021-02-26 21:42
Reviewers:  A proposed fix is in https://github.com/UCBerkeleySETI/turbo_seti/pull/199

**Closed** 2021-03-03 13:01 UTC
Labels: bug, review requested
