### ISSUE TITLE
Correct find_event.calc_freq_range()

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/turbo_seti#231] opened 2021-04-06 02:02 UTC
The function [calc_freq_range](https://github.com/UCBerkeleySETI/turbo_seti/blob/9819aed5fec65e20595e1eae523224926494de70/turbo_seti/find_event/find_event.py#L157) uses hardcoded values MAX_DRIFT_RATE and OBS_LENGTH. These should instead be derived from the data.

For the most part, this will mean extra events reported, not fewer events. The effect of using hardcoded MAX_DRIFT_RATE=2.0 will mean the hit boundaries are calculated assuming +/- 2 Hz, and area used for RFI coincidence detection will be too small for higher drift rates (meaning additional events detected). OBS_LENGTH assumes 5 minute observations, which will mean coincident detection is too small for longer observations.

**Comment by texadactyl** [comment] 2021-04-15 20:30
@telegraphic 

I started modifying find_event.py with the assumption that ```obs_length = float(hit['DELTAT'])```.  With this assumption, I saw an increaset in Voyager 2020 hits from 6 to 9 and not every hit appeared in every on-table (previously, they did).  So, many of the regression tests must change.

However, if OBS_LENGTH = 300 s = 5 minutes is the entirety of all the time integrations, then calc_freq_range does not have access.  The only time-related variable available is TDELTA (Filterbank header field tsamp).  The number of time integrations is in the h5 file header.

Please help me out here.

**Comment by texadactyl** [comment] 2021-04-15 20:38
Sample Voyager 2020 find_event_pipeline output CSV is attached.

[found_event_table.csv](https://github.com/UCBerkeleySETI/turbo_seti/files/6320992/found_event_table.csv)

**Comment by texadactyl** [comment] 2021-06-11 10:25
@telegraphic 

Torn between projects.  Cryptography is more time-consuming lately.  Not sure when I can have a look at this.

The ```hit``` object argument needs to be dumped by a debugger or print statements in real-time to get a feel for which data could be used.

**Comment by texadactyl** [comment] 2021-06-13 18:12
@telegraphic 

I see your points now.  In any case, I assigned this to you for the moment, if just for a review.  Got a new apprentice that you want to develop?

**Maximum Drift Rate vs Actual Drift Rate**

We need the defaulted or supplied maximum drift rate only known to FindDoppler (and then discarded) in this situation inside ```find_events```:
```
    #Now find how much RFI is within a frequency range of the hit 
    #by comparing the ON to the OFF observations. Update RFI_in_range
    if len(off_table) == 0:
        print('Length of off_table = 0')
        snr_adjusted_table['RFI_in_range'] = 0
    else:
        snr_adjusted_table['RFI_in_range'] = snr_adjusted_table.apply(
            lambda hit: 
                len(off_table[((off_table['Freq'] > calc_freq_range(hit)[0]) 
                               & (off_table['Freq'] < calc_freq_range(hit)[1])
                               )]), axis=1)
```

In ```follow_event```, the actual drift rate is used so no issue there.

**Observation Length**

Essentially, the ```header.nsamp``` and ```header.n_ints_in_file``` are needed to multiply together, producing the observation length.  This is required in both of the 2 situations described earlier.  Unfortunately, like the maximum drift rate, these 2 pieces of information are not available.

**Recommendation for Remediation**

* Amend turbo_seti to always write out a supplementary CSV file containing its run-time parameter values which would include, at minimum:
-- max_drift_rate
-- n_ints_in_file
-- tsamp

* The full path of this CSV file would be an additional argument for ```find_event_pipeline``` and ```find_events```.  Note that ```find_events``` can be called directly.

* The following routines need to be amended to work with the 3 parameters from the CSV file:
-- ```find_event_pipeline``` just pass along the CSV path
-- ```find_events``` df = pandas.read_csv
-- ```find_events``` use the df to pass along field values as needed
-- ```calc_freq_range``` new max_drift_rate and obs_length parameters
-- ```follow_event``` new obs_length parameter

**Comments/reactions?**

**Comment by telegraphic** [comment] 2021-06-28 03:00
Hi @texadactyl, I certainly agree that a supplementary file -- or putting this into the header of the existing CSV file -- would be a nice feature. Also for reproducability we could store the version of turboseti + blimpy used.

I am leaning slightly towards putting this into the existing CSV file. The issue here is that older versions of turboseti won't be able to read it, but it's one fewer file to keep track of! However if we decided to log a lot more information (e.g. dumping `pip freeze` output, IP address of server, the kitchen sink) then I a new file is a good idea.

This would instead mean updating `FileWriter` and `read_dat`
https://github.com/UCBerkeleySETI/turbo_seti/blob/42f072c06908d5c00483efcae0be93c46b10b9b6/turbo_seti/find_doppler/file_writers.py#L110
https://github.com/UCBerkeleySETI/turbo_seti/blob/master/turbo_seti/find_event/find_event.py#L43

As a sidenote, I will think about how hyperseti should output hits in CSV form, as it would be nice to keep as much interoperability as possible.

**Comment by texadactyl** [comment] 2021-06-28 17:00
@telegraphic 

The only way to put the new information in the existing CSV file is through DAT-style comments.  That's do-able.  Ugh! 
An alternative is to repeat the new information as new columns in each row.  Ugh again!  
I'd go with Ugh number 1.

I am not too worried about mixing turbo_seti installations and 2 different CSV file formats:
* The current/old versions of turbo_seti are not impacted at all as they will not generate nor read the modified CSV file.  The existing CSV file format and the design flaw is in place for them (consistent).
* If somehow (?) a new-format CSV file appeared in a current/old version of turbo_seti, the new DAT-style header (# statements) would not be processed as they appear to be comments.  Life would go on in the old design flaw manner.  I will make sure that the current processing can handle this odd case.
* After they upgrade to fix this issue, the new find_event_pipeline() should be re-run to produce the new CSV file format.  Then, the new plot_event_pipeline() will be re-run to process the new CSV file format. 
* If for some reason, plot_event_pipeline() is run on an old-format CSV file, it will fail due to missing information that it is expecting.  Part of the error report should note that find_event_pipeline() needs to be run first to recreate the new CSV file format.

**Comment by texadactyl** [comment] 2021-07-02 16:24
***Source Modification Approach***

**find_doppler.py and file_writers.py**
* max_drift_rate is already available as a parameter to FindDoppler object instantiation.
* Calculate obs_length = header.nsamp * header.n_ints_in_file.
* Append the DAT "# DELTAT" line with max_drift_rate and obs_length.

**find_events.py**
* read_dat: extract max_drift_rate and obs_length from the DAT file and pass them back to caller along with the dataframe.
* make_table: merge into read_dat.  So, read_dat returns to find_events in 2 places: on-table and off-table.
* find_events: accept max_drift_rate and obs_length in addition to dataframe as return variables from read_dat.
* find_events: off_table: pass hit, max_drift_rate, and obs_length to calc_freq_range.
* find_events: on_table: pass hit and obs_length to calc_freq_range.  Use the hit's drift rate.
* calc_freq_range: use parametric values instead of hard-coded constants.

**Comment by texadactyl** [comment] 2021-07-02 23:06
**Impacted software**

turbo_seti/find_doppler/
- data_handler.py
- file_writers.py
- find_doppler.py

turbo_seti/find_event/
- find_event.py

test/
- test_find_event.py
- test_pipelines_3.py

**Closed** 2021-07-03 00:44 UTC
Labels: design flaw
