### ISSUE TITLE
turboSETI hangs when it runs into a file with fewer than 4 rows

### ISSUE THREAD

**Issue by lacker** [UCBerkeleySETI/turbo_seti#255] opened 2021-07-15 18:26 UTC
**Describe the bug**

When you run turboSETI on a file with only 2 rows of data, it fails and prints a message, but the process does not exit, it keeps running doing nothing.

**Relevant BL files (.fil, .h5)**

You can reproduce this from the `blpc0` machine with:

```
turboSETI /datag/pipeline/AGBT21A_996_44/blc04/blc04_guppi_59383_70047_3C123_0104.rawspec.0000.h5
```

Notice how the process does not exit after failing

**Expected behavior**

The process exits after failing

**Setup**

- Python version: 3.8
- turbo_seti version 2.1.0
- blimpy version 2.0.15
- h5py version 3.2.1

**Comment by texadactyl** [comment] 2021-07-15 18:57
I do not see a hang.  The turbo_seti process terminates after the trace back:

**Comment by lacker** [comment] 2021-07-15 19:11
Here's the output I get.

```
(pipeline) obs@blpc0:~/xxx$ turboSETI /datag/pipeline/AGBT21A_996_44/blc04/blc04_guppi_59383_70047_3C123_0104.rawspec.0000.h5
Info: Your system is compatible with GPU-mode. Use the `-g y` argument to enable it.

turbo_seti version 2.1.0
blimpy version 2.0.15
h5py version 3.2.1

HDF5 header info: {'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 7688.96484375, 'foff': -2.7939677238464355e-06, 'ibeam': -1, 'machine_id': 20, 'nbeams': 1, 'nbits': 32, 'nchans': 67108864, 'nifs': 1, 'rawdatafile': 'guppi_59383_70047_3C123_0104.0000.raw', 'source_name': '3C123', 'src_dej': <Angle 29.67081722 deg>, 'src_raj': <Angle 4.61788333 hourangle>, 'telescope_id': 6, 'tsamp': 18.253611007999982, 'tstart': 59383.81072916667, 'za_start': 0.0}

Starting ET search with parameters: datafile=/datag/pipeline/AGBT21A_996_44/blc04/blc04_guppi_59383_70047_3C123_0104.rawspec.0000.h5, max_drift=10.0, min_drift=1e-05, snr=25.0, out_dir=./, coarse_chans=, flagging=False, n_coarse_chan=64, kernels=None, gpu_backend=False, precision=2, append_output=False, log_level_int=20, obs_info={'pulsar': 0, 'pulsar_found': 0, 'pulsar_dm': 0.0, 'pulsar_snr': 0.0, 'pulsar_stats': array([0., 0., 0., 0., 0., 0.]), 'RFI_level': 0.0, 'Mean_SEFD': 0.0, 'psrflux_Sens': 0.0, 'SEFDs_val': [0.0], 'SEFDs_freq': [0.0], 'SEFDs_freq_up': [0.0]}

Computed drift rate resolution: 0.0765319180578004

data_handler    ERROR    data_handler.py:load_drift_indexes: tsteps=2!
data_handler    ERROR    data_handler.py:load_drift_indexes: drift_indexes/drift_indexes_array_1.txt not found!
Traceback (most recent call last):
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/site-packages/turbo_seti/find_doppler/seti_event.py", line 136, in exec_proc
    find_seti_event.search(n_partitions=args.n_parallel,
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/site-packages/turbo_seti/find_doppler/find_doppler.py", line 202, in search
    search_coarse_channel(dl, self, dataloader=sched, filewriter=filewriter, logwriter=logwriter)
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/site-packages/turbo_seti/find_doppler/find_doppler.py", line 277, in search_coarse_channel
    data_obj, spectra, drift_indices = dataloader.get()
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/site-packages/turbo_seti/find_doppler/kernels/Scheduler/__init__.py", line 36, in get
    result = f.result()
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/site-packages/turbo_seti/find_doppler/find_doppler.py", line 226, in load_the_data
    spectra, drift_indices = data_obj.load_data()
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/site-packages/turbo_seti/find_doppler/data_handler.py", line 300, in load_data
    drift_indexes = self.load_drift_indexes()
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/site-packages/turbo_seti/find_doppler/data_handler.py", line 324, in load_drift_indexes
    raise ValueError("""Don't attempt to use High Time Resolution (HRT) files with turboSETI. """
ValueError: Don't attempt to use High Time Resolution (HRT) files with turboSETI. TurboSETI is designed to search for narrowband signals -- the maximum doppler drift we can expect due to the motion of celestial bodies is a few Hz/s. The high time resolution products (ending 0001.fil) has ~0.5 MHz resolution and ~100 us integrations, so you'd be looking at insane drift rates. Issue #117.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/obs/miniconda3/envs/pipeline/bin/turboSETI", line 8, in <module>
    sys.exit(main())
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/site-packages/turbo_seti/find_doppler/seti_event.py", line 87, in main
    exec_proc(args)
  File "/home/obs/miniconda3/envs/pipeline/lib/python3.8/site-packages/turbo_seti/find_doppler/seti_event.py", line 143, in exec_proc
    raise RuntimeError('[turboSETI] An exception occured in FindDoppler.') from e
RuntimeError: [turboSETI] An exception occured in FindDoppler.
```

**Comment by texadactyl** [comment] 2021-07-15 20:51
Cannot reproduce your findings with the exact same versions of application software:
- turbo_seti version 2.1.0
- blimpy version 2.0.15
- h5py version 3.2.1

The only difference is that I am running Python 3.9.5.

In the data centre node blpc0, I also cannot reproduce your findings.  Running Python 3.7.6 there.

**Comment by texadactyl** [comment] 2021-07-15 21:02
Closing this issue for now since I cannot proceed further.

**Closed by texadactyl** 2021-07-15 21:02 UTC
