### ISSUE TITLE
Red line overlaid on plot_event waterfall plots doesn't approximate signals' drift rates

### ISSUE THREAD

**Issue by ewhite42** [UCBerkeleySETI/turbo_seti#152] opened 2021-01-04 14:25 UTC
I noticed when running plot_event_pipeline on the Voyager data linked from [https://github.com/UCBerkeleySETI/turbo_seti/issues/150](https://github.com/UCBerkeleySETI/turbo_seti/issues/150) that the red line overlaid to approximate the drift rate appears to have the opposite slope as the drifting signal itself across the spectrogram: 

![table csv_VOYAGER-1_dr_-0 43_freq_8419 541272](https://user-images.githubusercontent.com/27837295/103544007-65211200-4e6d-11eb-835c-96cc518c6866.png)

I made a local copy of plot_event.py and attempted to troubleshoot this issue, and found that if I change line 52 from 

```
plt.plot((f_event + offset, f_event + drift_rate/1e6 * t_duration + offset),
             (0, t_duration),
             c='#cc0000',
             ls='dashed', lw=2)plt.plot((f_event + offset, f_event - drift_rate/1e6 * t_duration + offset),
             (0, t_duration),
             c='#cc0000',
             ls='dashed', lw=2)
```

to:

```
plt.plot((f_event + offset, f_event - drift_rate/1e6 * t_duration + offset),
             (0, t_duration),
             c='#cc0000',
             ls='dashed', lw=2)plt.plot((f_event + offset, f_event - drift_rate/1e6 * t_duration + offset),
             (0, t_duration),
             c='#cc0000',
             ls='dashed', lw=2)
```
(notice the second plus sign gets changed to a minus sign), and then if I also change the code in line 219 from: 

`f_event = f_mid + drift_rate / 1e6 * t_elapsed`

to:

`f_event = f_mid - drift_rate / 1e6 * t_elapsed`

then that seems to mitigate the issue, at least on this particular dataset; this is what the same plot looks like after the fix has been applied in my local copy of plot_event: 

![table csv_VOYAGER-1_dr_-0 43_freq_8419 541272](https://user-images.githubusercontent.com/27837295/103544629-64d54680-4e6e-11eb-992f-c896b440388b.png)

**Comment by texadactyl** [comment] 2021-01-04 15:36
Incorporated this fix to plot_event.py in turbo_seti version 2.0.5.
Excellent bug fix!

**Comment by texadactyl** [comment] 2021-01-04 16:23
Did we move from one constant slope to another?
Parkes data: http://blpd0.ssl.berkeley.edu/parkes_testing/

**Comment by texadactyl** [comment] 2021-01-04 17:25
The following lower drift rate Parkes PNG files seem to make sense:

![f2_HIP33499_S_dr_-0 01_freq_2673 746750](https://user-images.githubusercontent.com/11318756/103561608-622f1d00-4e7f-11eb-8a9a-94945084fc2f.png)
![f2_HIP33499_S_dr_-0 01_freq_2673 973349](https://user-images.githubusercontent.com/11318756/103561611-622f1d00-4e7f-11eb-9f51-d7eb079fba65.png)
![f2_HIP33499_S_dr_-0 01_freq_2674 009349](https://user-images.githubusercontent.com/11318756/103561612-62c7b380-4e7f-11eb-8abe-04a60a6a11a0.png)
![f2_HIP33499_S_dr_-0 01_freq_2674 053950](https://user-images.githubusercontent.com/11318756/103561614-62c7b380-4e7f-11eb-8303-033734d0ed39.png)
![f2_HIP33499_S_dr_-0 01_freq_2674 055950](https://user-images.githubusercontent.com/11318756/103561615-63604a00-4e7f-11eb-8bc8-7b71e3263b94.png)
![f2_HIP33499_S_dr_-0 01_freq_2674 104749](https://user-images.githubusercontent.com/11318756/103561616-63604a00-4e7f-11eb-9d87-08f6e35b6474.png)

**Comment by stevecroft** [comment] 2021-01-05 00:50
Comparing @ewhite42 's plots above with Elan's plots in https://github.com/elanlavie/VoyagerTutorial2/blob/master/VoyagerTutorial(1).ipynb the sign of the slope in the latter appears to be correct, although Elan was using some older bespoke version of plot_event by @Sofysicist. Would be worth comparing these versions of plot_event to see where this bug is occuring.

**Comment by texadactyl** [comment] 2021-01-05 13:42
The following 2 messages will show 2 sets of Voyager 2020 PNGs (6):

**Comment by texadactyl** [comment] 2021-01-05 13:47
The following 2 messages will show 2 sets of Voyager 2020 PNGs (6):
1. plot_event.py from current (2.0.5) turbo_seti 
2. plot_event.py extracted from https://github.com/Sofysicist/turbo_seti (last update on 7/22/2020)

**Comment by texadactyl** [comment] 2021-01-05 13:48
plot_event.py from current (2.0.5) turbo_seti

![f3_VOYAGER-1_dr_-0 35_freq_8419 541938](https://user-images.githubusercontent.com/11318756/103653561-50568400-4f2a-11eb-8bab-c02f91c8729c.png)
![f3_VOYAGER-1_dr_-0 36_freq_8419 564576](https://user-images.githubusercontent.com/11318756/103653562-50568400-4f2a-11eb-966d-44b587adcc15.png)
![f3_VOYAGER-1_dr_-0 38_freq_8419 541636](https://user-images.githubusercontent.com/11318756/103653564-50ef1a80-4f2a-11eb-884d-79b27ea808b6.png)
![f3_VOYAGER-1_dr_-0 40_freq_8419 564252](https://user-images.githubusercontent.com/11318756/103653565-50ef1a80-4f2a-11eb-81b8-a11296d78e26.png)
![f3_VOYAGER-1_dr_-0 41_freq_8419 563969](https://user-images.githubusercontent.com/11318756/103653568-5187b100-4f2a-11eb-8fc0-7e0e4bff7572.png)
![f3_VOYAGER-1_dr_-0 43_freq_8419 541272](https://user-images.githubusercontent.com/11318756/103653569-5187b100-4f2a-11eb-87dc-33cab908473a.png)

**Comment by texadactyl** [comment] 2021-01-05 13:48
plot_event.py extracted from https://github.com/Sofysicist/turbo_seti (last update on 7/22/2020)

![f3_VOYAGER-1_dr_-0 35_freq_8419 541938](https://user-images.githubusercontent.com/11318756/103653636-6cf2bc00-4f2a-11eb-8fc9-f26a32af90fe.png)
![f3_VOYAGER-1_dr_-0 36_freq_8419 564576](https://user-images.githubusercontent.com/11318756/103653638-6d8b5280-4f2a-11eb-938a-23eb9ea022e6.png)
![f3_VOYAGER-1_dr_-0 38_freq_8419 541636](https://user-images.githubusercontent.com/11318756/103653642-6e23e900-4f2a-11eb-9d27-34321a374319.png)
![f3_VOYAGER-1_dr_-0 40_freq_8419 564252](https://user-images.githubusercontent.com/11318756/103653645-6e23e900-4f2a-11eb-9d19-8fd5a167f2e7.png)
![f3_VOYAGER-1_dr_-0 41_freq_8419 563969](https://user-images.githubusercontent.com/11318756/103653647-6e23e900-4f2a-11eb-8e58-9920e6e806ba.png)
![f3_VOYAGER-1_dr_-0 43_freq_8419 541272](https://user-images.githubusercontent.com/11318756/103653648-6ebc7f80-4f2a-11eb-8f9b-2a5964dff34b.png)

**Comment by texadactyl** [comment] 2021-01-05 13:53
I used plot_event.py extracted from https://github.com/Sofysicist/turbo_seti (last update on 7/22/2020) in addition to plot_event.py in the current (2.0.5) turbo_seti.  So, I produced 2 comparable sets of 6 PNG files and shared them with @ewhite42 and Elan.

**Comment by ewhite42** [comment] 2021-01-05 16:06
After installing the current turboSETI (2.0.5) and running it on my local computer, I'm seeing identical results to those in @texadactyl 's zip file. I went back and compared with the plots from Elan's Jupyter notebook tutorial (https://github.com/elanlavie/VoyagerTutorial2) and they appear to match up as well. :)

**Comment by stevecroft** [comment] 2021-01-05 17:46
Good that they match now, although I'm confused as to what point the bug resulting in the reversed drift plot shown in Ellie's original post above was introduced.

**Comment by stevecroft** [comment] 2021-01-05 19:02
I think actually the x-axis labelling is flipped too - compare Elan's plots with frequency decreasing to the right (which appears to be consistent with the computed drift rate, -0.4 Hz / s). Supposedly this was using some code from @Sofysicist although I don't know what version. Seems like sign errors have crept in at some point - would be good to figure out when.

**Comment by texadactyl** [comment] 2021-01-05 21:07
Code from @Sofysicist did get integrated correctly.  It works fine.  I found the issue in a 7/28 update and have corrected it (might have been ok in July but ?).  I will run regression testing.  If all goes well, I'll have a 2.0.6 soon after.

Corrected plots:
![f3_VOYAGER-1_dr_-0 35_freq_8419 541938](https://user-images.githubusercontent.com/11318756/103698424-f88a3e00-4f66-11eb-9876-92a5a2d87bba.png)
![f3_VOYAGER-1_dr_-0 36_freq_8419 564576](https://user-images.githubusercontent.com/11318756/103698432-f922d480-4f66-11eb-9fbd-18a0b77ddd98.png)
![f3_VOYAGER-1_dr_-0 38_freq_8419 541636](https://user-images.githubusercontent.com/11318756/103698434-f922d480-4f66-11eb-801e-d0e2d26f1e8c.png)
![f3_VOYAGER-1_dr_-0 40_freq_8419 564252](https://user-images.githubusercontent.com/11318756/103698435-f9bb6b00-4f66-11eb-8a08-04029d2f0244.png)
![f3_VOYAGER-1_dr_-0 41_freq_8419 563969](https://user-images.githubusercontent.com/11318756/103698436-f9bb6b00-4f66-11eb-917f-878ea67ed447.png)
![f3_VOYAGER-1_dr_-0 43_freq_8419 541272](https://user-images.githubusercontent.com/11318756/103698438-fa540180-4f66-11eb-8c75-76906c51b7a4.png)

**Comment by texadactyl** [comment] 2021-01-06 22:31
@ssmith00 - note that this was fixed by yanking the PR #82 code.  We should talk about Parkes UWL data that you were concerned about back then.  Maybe there is another way.

**Comment by texadactyl** [comment] 2021-01-09 20:52
@luigi discussion above FYI

**Comment by texadactyl** [comment] 2021-01-21 17:04
Since this was identified and addressed in the Voyager August 2020 data, I will close this issue.  This does not mean that anyone believes that plotting is perfect.

Please raise an issue if another case is found, specifying WHICH input file (.fil or .h5) will exhibit errant symptoms.

**Closed by texadactyl** 2021-01-21 17:04 UTC
Labels: bug
